/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.open_policy_agent.opa.openapi.utils;

import tools.jackson.core.JsonGenerator;
import tools.jackson.core.JsonParser;
import tools.jackson.databind.DeserializationContext;
import tools.jackson.databind.SerializationContext;
import tools.jackson.databind.annotation.JsonDeserialize;
import tools.jackson.databind.annotation.JsonSerialize;
import tools.jackson.databind.deser.std.StdDeserializer;
import tools.jackson.databind.ser.std.StdSerializer;

import java.math.BigInteger;
import java.util.Objects;

// Internal API only

// Note that Jackson 2.16.1 does not support @JsonValue and @JsonFormat combined so we must use
// a custom serializer/deserializer

@JsonSerialize(using = BigIntegerString.Serializer.class)
@JsonDeserialize(using = BigIntegerString.Deserializer.class)
public class BigIntegerString {

    private final BigInteger value;

    public BigIntegerString(BigInteger value) {
        this.value = value;
    }
    
    public BigIntegerString(String value) {
        this(new BigInteger(value));
    }
    
    public BigInteger value() {
        return value;
    }
    
    @Override
    public String toString() {
        return value.toString();
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        BigIntegerString other = (BigIntegerString) obj;
        return Objects.equals(value, other.value);
    }
    
    public static final class Serializer extends StdSerializer<BigIntegerString> {

        protected Serializer() {
            super(BigIntegerString.class);
        }

        @Override
        public void serialize(BigIntegerString value, JsonGenerator g, SerializationContext ctxt) {
            g.writeString(value.value.toString());
        }
    }

    public static final class Deserializer extends StdDeserializer<BigIntegerString> {

        protected Deserializer() {
            super(BigIntegerString.class);
        }

        @Override
        public BigIntegerString deserialize(JsonParser p, DeserializationContext ctxt) {
            String s = p.readValueAs(String.class);
            return new BigIntegerString(new BigInteger(s));
        }
    }
}
