/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.open_policy_agent.opa.openapi.utils;

import tools.jackson.core.JsonParser;
import tools.jackson.core.JsonToken;
import tools.jackson.databind.DeserializationContext;
import tools.jackson.databind.ValueDeserializer;
import tools.jackson.databind.deser.std.StdDeserializer;
import tools.jackson.databind.module.SimpleModule;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

public final class Deserializers {

    public static final ValueDeserializer<Boolean> BOOLEAN_STRICT = new StrictBooleanDeserializer();
    public static final ValueDeserializer<Integer> INTEGER_STRICT = new StrictIntegerDeserializer();
    public static final ValueDeserializer<Long> LONG_STRICT = new StrictLongDeserializer();
    public static final ValueDeserializer<Short> SHORT_STRICT = new StrictShortDeserializer();
    public static final ValueDeserializer<Float> FLOAT_STRICT = new StrictFloatDeserializer();
    public static final ValueDeserializer<Double> DOUBLE_STRICT = new StrictDoubleDeserializer();
    public static final ValueDeserializer<LocalDate> LOCAL_DATE_STRICT = new StrictLocalDateDeserializer();
    public static final ValueDeserializer<OffsetDateTime> OFFSET_DATE_TIME_STRICT = new StrictOffsetDateTimeDeserializer();
    public static final ValueDeserializer<String> STRING_STRICT = new StrictStringDeserializer();

    public static final SimpleModule STRICT_DESERIALIZERS = createStrictDeserializersModule();

    private static SimpleModule createStrictDeserializersModule() {
        SimpleModule m = new SimpleModule();
        m.addDeserializer(Boolean.class, Deserializers.BOOLEAN_STRICT);
        m.addDeserializer(Short.class, Deserializers.SHORT_STRICT);
        m.addDeserializer(Integer.class, Deserializers.INTEGER_STRICT);
        m.addDeserializer(Long.class, Deserializers.LONG_STRICT);
        m.addDeserializer(Float.class, Deserializers.FLOAT_STRICT);
        m.addDeserializer(Double.class, Deserializers.DOUBLE_STRICT);
        m.addDeserializer(OffsetDateTime.class, Deserializers.OFFSET_DATE_TIME_STRICT);
        m.addDeserializer(LocalDate.class, Deserializers.LOCAL_DATE_STRICT);
        m.addDeserializer(String.class, Deserializers.STRING_STRICT);
        return m;
    }
    
    private static final class StrictBooleanDeserializer extends StdDeserializer<Boolean> {

        StrictBooleanDeserializer() {
            super(Boolean.class);
        }

        @Override
        public Boolean deserialize(JsonParser p, DeserializationContext ctxt) {
            JsonToken t = p.currentToken();
            if (t == JsonToken.VALUE_TRUE) {
                return true;
            } else if (t == JsonToken.VALUE_FALSE) {
                return false;
            } else {
                return (Boolean) ctxt.handleUnexpectedToken(Boolean.class, p);
            }
        }
    }
    
    private static final class StrictDoubleDeserializer extends StdDeserializer<Double> {

        StrictDoubleDeserializer() {
            super(Double.class);
        }

        @Override
        public Double deserialize(JsonParser p, DeserializationContext ctxt) {
            JsonToken t = p.currentToken();
            if (t == JsonToken.VALUE_NUMBER_INT) {
                return p.getDoubleValue();
            } else if (t == JsonToken.VALUE_NUMBER_FLOAT) {
                return p.getDoubleValue();
            } else {
                return (Double) ctxt.handleUnexpectedToken(Double.class, p);
            }
        }
    }

    private static final class StrictFloatDeserializer extends StdDeserializer<Float> {

        StrictFloatDeserializer() {
            super(Float.class);
        }

        @Override
        public Float deserialize(JsonParser p, DeserializationContext ctxt) {
            JsonToken t = p.currentToken();
            if (t == JsonToken.VALUE_NUMBER_INT) {
                return p.getFloatValue();
            } else if (t == JsonToken.VALUE_NUMBER_FLOAT) {
                return p.getFloatValue();
            } else {
                return (Float) ctxt.handleUnexpectedToken(Float.class, p);
            }
        }
    }
    
    private static final class StrictIntegerDeserializer extends StdDeserializer<Integer> {

        StrictIntegerDeserializer() {
            super(Integer.class);
        }

        @Override
        public Integer deserialize(JsonParser p, DeserializationContext ctxt) {
            JsonToken t = p.currentToken();
            if (t == JsonToken.VALUE_NUMBER_INT) {
                return p.getIntValue();
            } else {
                return (Integer) ctxt.handleUnexpectedToken(Integer.class, p);
            }
        }
    }

    private static final class StrictLocalDateDeserializer extends StdDeserializer<LocalDate> {

        StrictLocalDateDeserializer() {
            super(LocalDate.class);
        }

        @Override
        public LocalDate deserialize(JsonParser p, DeserializationContext ctxt) {
            if (p.currentToken() == JsonToken.VALUE_STRING) {
                String text = p.getString();
                try {
                    return LocalDate.parse(text, DateTimeFormatter.ISO_LOCAL_DATE);
                } catch (DateTimeParseException e) {
                    return (LocalDate) ctxt.handleWeirdStringValue(LocalDate.class, text, e.getMessage());
                }
            } else {
                return (LocalDate) ctxt.handleUnexpectedToken(LocalDate.class, p);
            }
        }
    }

    private static final class StrictLongDeserializer extends StdDeserializer<Long> {

        public StrictLongDeserializer() {
            super(Long.class);
        }

        @Override
        public Long deserialize(JsonParser p, DeserializationContext ctxt) {
            JsonToken t = p.currentToken();
            if (t == JsonToken.VALUE_NUMBER_INT) {
                return p.getLongValue();
            } else {
                return (Long) ctxt.handleUnexpectedToken(Long.class, p);
            }
        }
    }

    private static final class StrictOffsetDateTimeDeserializer extends StdDeserializer<OffsetDateTime> {

        StrictOffsetDateTimeDeserializer() {
            super(OffsetDateTime.class);
        }

        @Override
        public OffsetDateTime deserialize(JsonParser p, DeserializationContext ctxt) {
            if (p.currentToken() == JsonToken.VALUE_STRING) {
                String text = p.getString();
                try {
                    return OffsetDateTime.parse(text, DateTimeFormatter.ISO_DATE_TIME);
                } catch (DateTimeParseException e) {
                    return (OffsetDateTime) ctxt.handleWeirdStringValue(OffsetDateTime.class, text, e.getMessage());
                }
            } else {
                return (OffsetDateTime) ctxt.handleUnexpectedToken(OffsetDateTime.class, p);
            }
        }
    }

    private static final class StrictShortDeserializer extends StdDeserializer<Short> {

        StrictShortDeserializer() {
            super(Short.class);
        }

        @Override
        public Short deserialize(JsonParser p, DeserializationContext ctxt) {
            JsonToken t = p.currentToken();
            if (t == JsonToken.VALUE_NUMBER_INT) {
                return p.getShortValue();
            } else {
                return (Short) ctxt.handleUnexpectedToken(Short.class, p);
            }
        }
    }

    private static final class StrictStringDeserializer extends StdDeserializer<String> {

        StrictStringDeserializer() {
            super(String.class);
        }

        @Override
        public String deserialize(JsonParser p, DeserializationContext ctxt) {
            JsonToken t = p.currentToken();
            if (t == JsonToken.VALUE_STRING) {
                return p.getString();
            } else {
                return (String) ctxt.handleUnexpectedToken(String.class, p);
            }
        }
    }
}
