/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.open_policy_agent.opa.openapi.utils;

/**
 * Implemented by classes that have security annotations on fields.
 **/
public interface HasSecurity {
}