/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.open_policy_agent.opa.openapi.utils;

import org.openapitools.jackson.nullable.JsonNullableJackson3Module;
import tools.jackson.databind.DeserializationFeature;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.SerializationFeature;
import tools.jackson.databind.json.JsonMapper;

public class JSON {
    public static ObjectMapper getMapper() {
        return JsonMapper.builder()
                .addModule(new JsonNullableJackson3Module())
                .addModule(Deserializers.STRICT_DESERIALIZERS)
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                .disable(SerializationFeature.FAIL_ON_EMPTY_BEANS)
                .enable(DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES)
                .build();
    }
}