/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.open_policy_agent.opa.openapi.utils;

import io.github.open_policy_agent.opa.openapi.utils.Utils.JsonShape;
import tools.jackson.core.JsonGenerator;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.SerializationContext;
import tools.jackson.databind.annotation.JsonSerialize;
import tools.jackson.databind.ser.std.StdSerializer;

@JsonSerialize(using = TypedObject.Serializer.class)
public class TypedObject {

    private final Object value;
    private final TypeReference<?> typeReference;
    private final JsonShape shape;

    private TypedObject(Object value, JsonShape shape, TypeReference<?> typeReference) {
        this.value = value;
        this.shape = shape;
        this.typeReference = typeReference;
    }

    public Object value() {
        return value;
    }

    public TypeReference<?> typeReference() {
        return typeReference;
    }

    public JsonShape shape() {
        return shape;
    }
    
    @Override
    public String toString() {
        return String.valueOf(value);
    }
    
    public static <T> TypedObject of(T value, JsonShape shape, TypeReference<T> typeReference) {
        return new TypedObject(value, shape, typeReference);
    }

    public static final class Serializer extends StdSerializer<TypedObject> {

        public Serializer() {
            super(TypedObject.class);
        }

        @Override
        public void serialize(TypedObject value, JsonGenerator gen, SerializationContext ctxt) {
            Object o = Utils.convertToShape(value.value(),value.shape(), value.typeReference());
            ctxt.findValueSerializer(o.getClass()).serialize(o, gen, ctxt);
        }

    }
}
