name: Publish Docs
"on":
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  docs:
    rname: Docs Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for pushing changes to Github Pages.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true # Needed for the Github Pages deployment.
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          cache-disabled: true
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: ./scripts/build_docs.sh ./build/docsite
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docsite