name: "Publish to Maven Central"
"on":
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  publish:
    name: Publish Java SDK
    runs-on: ubuntu-latest
    steps:
      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "gradle"
      - uses: gradle/actions/setup-gradle@v4
      - name: Get current Gradle project version
        id: gradle-version
        run: |
          VERSION="version=$(./gradlew properties | grep "^version:" | cut -d' ' -f2)"
          echo $VERSION
          echo $VERSION >> $GITHUB_OUTPUT
      - name: Get current Maven project version
        id: maven-version
        run: |
          VERSION="version=$(curl -s "https://repo1.maven.org/maven2/io/github/open-policy-agent/opa/maven-metadata.xml"
          echo $VERSION
          echo $VERSION | grep -o '<latest>[^<]*</latest>' | sed 's/<[^>]*>//g')" >> $GITHUB_OUTPUT
      - name: Publish to Sonatype Central
        if: ${{ steps.gradle-version.outputs.version != steps.maven-version.outputs.version }}
        run: |-
          pwd
          ./gradlew build sonatypeCentralUpload --no-daemon
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_SIGNING_KEY: ${{ secrets.JAVA_GPG_SECRET_KEY }}
          SIGNING_KEY_PASSPHRASE: ${{ secrets.JAVA_GPG_PASSPHRASE }}
