/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openpolicyagent.opa.openapi.models.operations;

import org.openpolicyagent.opa.openapi.utils.Utils;
import java.lang.Exception;

public class ExecuteBatchPolicyWithInputRequestBuilder {

    private ExecuteBatchPolicyWithInputRequest request;
    private final SDKMethodInterfaces.MethodCallExecuteBatchPolicyWithInput sdk;

    public ExecuteBatchPolicyWithInputRequestBuilder(SDKMethodInterfaces.MethodCallExecuteBatchPolicyWithInput sdk) {
        this.sdk = sdk;
    }

    public ExecuteBatchPolicyWithInputRequestBuilder request(ExecuteBatchPolicyWithInputRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ExecuteBatchPolicyWithInputResponse call() throws Exception {

        return sdk.executeBatchPolicyWithInput(
            request);
    }
}
